### ISSUE TITLE
Test Numbers

### ISSUE THREAD

**Issue by bartervoip** [telecomsxchange/react-apps-getnumbers#2]
Dear Team,
At present we are able to get Test Numbers based on "Prefix or Country Code" only (only Numerals are allowed). If we can get the Test Numbers based on Country Name+Code Type+Operator (Alpha Characters), it would be very useful for us. For example, if we want to get a Test Number for "India Mobile Airtel" (India - Country, Mobile - Code Type and Airtel - Operator) it is not possible in the present scenario. In most of the cases, we prefer to search for the Test Numbers based on Country+Code Type+Operator only. Whether it is a manual search or API calls. In both ways, it needs to be allowed.

**Comment by telecomsxchange** [comment]
@bartervoip to achieve this we have to add country, description based support to the Get Numbers API first.

do you plan to use a custom front-end for the API or do you want this feature to be added to this react project UI ?

**Comment by telecomsxchange** [comment]
@bartervoip we have added the support for country name and description parameters in the API. You can use it now to achieve the functionality your looking for. 

https://documenter.getpostman.com/view/5344044/SVtbPk6K?version=latest#e3ab2e21-a698-452f-b0ef-d59872dbafba
